 version: "3.7"

 services:
  app: 
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ./static:/opt/static
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - PORT=5001
    ports: 
      - 5001:5001
    depends_on:
      - db
    command: npm run start

  db:
    image: postgres:14-alpine
    user: ${DB_USER}
    volumes:
      - app-data:/var/lib/postgresql/data
    environment:      
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    ports:
      - '5432:5432'

  nginx:
    container_name: nginx
    depends_on:
      - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always
  
  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: viopar@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 30031995Aa
    expose:
      - '80'
    restart: always

 volumes:
   app-data:
   