 version: "3.7"

 services:
  app: 
    image: node:16-alpine
    command: sh -c "npm i && npm run dev"
    ports: 
      - 5000:5000
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - ./static:/opt/static
    environment:
      DB_NAME: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      PORT: ${PORT}
  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:      
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - '5432:5432'

  nginx:
    container_name: nginx
    depends_on:
      - app
      - db
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always
  
 volumes:
   app-data:
   